### ISSUE TITLE
add logic for "third place from group A/B/C"

### ISSUE THREAD

**Issue by tompson** [troii/Rudeltippen#8]
the best 4 teams from the third place in the groups will be promoted to the playoffs, the current logic has no way to describe this

**Comment by tompson** [comment]
I looked at http://www.em2016.net/em-2016-turniermodus and decided not implement this, the rules are to complicated, we need to add the playoff games manually

**Comment by littleStudent** [comment]
should not be a problem, the site is very mobile responsive. can be done immediately after the games are finished.
